stages:
  stage_01:
    cmd: python stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifects_01.txt

  stage_02:
    cmd: python stage_02.py
    deps:
      -  artifects_01.txt
      -  stage_02.py

  stage_03:
    cmd: python stage_03.py
    deps:
      -  artifects_01.txt
      -  stage_03.py
    outs:
      - artifects_02.txt
